# Generated by Django 4.0.3 on 2022-03-30 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z]{1}[a-z]{1,19})$', 'Name must start with capital letter and contain from 2 to 20 letters. Example: Andriy')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380[\\d]{9}$', 'Invalid phone number. Example: +380xxxxxxxxx')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z]{1}[a-z]{1,19})$', 'Surname must start with capital letter and contain from 2 to 20 letters. Example: Popov')]),
        ),
    ]
