# Generated by Django 4.0.3 on 2022-04-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',), 'verbose_name': 'Car'},
        ),
    ]
