# Generated by Django 4.0.3 on 2022-03-30 18:52

import django.core.validators
from django.db import migrations, models
import utils.avatar_util


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_profilemodel_name_alter_profilemodel_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=utils.avatar_util.AvatarUtils.upload_to),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z]{1}[a-z]{1,19})$', 'Name must start with the capital letter and contain from 2 to 20 letters. Example: Andriy')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^([A-Z]{1}[a-z]{1,19})$', 'Surname must start with the capital letter and contain from 2 to 20 letters. Example: Popov')]),
        ),
    ]
