# Generated by Django 4.0.3 on 2022-04-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('id',)},
        ),
    ]
