# Generated by Django 4.0.3 on 2022-03-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('ram', models.IntegerField()),
                ('display_size', models.FloatField()),
            ],
            options={
                'db_table': 'computers',
            },
        ),
    ]
